FROM registry.suse.com/bci/rust:latest as susebuild
WORKDIR /src
RUN zypper install -y libpcap1 libpcap-devel
COPY Cargo.toml /src/
COPY Cargo.lock /src/
COPY src /src/src
RUN cargo build && cargo test
RUN cargo build --release

FROM registry.suse.com/bci/bci-base:latest
RUN zypper install -y libpcap1
COPY --from=susebuild /src/target/release/rustintrace /rustintrace
ENTRYPOINT ["/rustintrace"]
